BaSP-MR-17: initial setup complete
BaSP-m2023/ferpa-megarocket-server pull request #35
Opened 2023-05-19 20:37 UTC by IgnacioCanton

all initial setup finished. please review so I can merge it.

2023-05-19 20:42 UTC, LucianoStradiot approved these changes

2023-05-19 20:43 UTC, VictoriaNegrotto approved these changes
looks good

2023-05-19 20:43 UTC, matiasluispeter approved these changes
seems good to me!!

2023-05-19 20:44 UTC, NicolasKler approved these changes
Looks good to me

2023-05-19 20:45 UTC, leo-balonchard approved these changes
Looks good

2023-05-19 22:07 UTC, Juanoauil requested changes

2023-05-19 22:07 UTC, Juanoauil commented on src/index.js
> -  .connect(DB_URL, { maxPoolSize: process.env.MONGO_POOLSIZE || 1 })
Please revert this change, you must set with `maxPoolSize`

2023-05-20 16:07 UTC, Juanoauil approved these changes

2023-05-20 16:08 UTC, merged